# Generated by Django 5.0 on 2025-01-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommendations",
            "0004_abtest_productcollection_usersegment_abtestvariant_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationexplanation",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanations",
                to="recommendations.recommendation",
            ),
        ),
    ]
