# Generated by Django 5.1.3 on 2025-01-04 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0006_alter_category_options_category_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
